# Generated by Django 3.2.16 on 2022-12-16 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=350)),
                ('Image', models.ImageField(upload_to='pic')),
                ('dscrpt', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='own',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.CharField(max_length=350)),
                ('snap', models.ImageField(upload_to='pics')),
                ('dsta', models.TextField()),
            ],
        ),
    ]
